imageType:
  Original: {} # for dictionaries / mappings, None values are not allowed, '{}' is interpreted as an empty dictionary

featureClass:
  glcm:
  glrlm: 
  glszm:
  gldm:  
  ngtdm:

setting:
  binWidth: 56
  label: 1
  interpolator: 'sitkBSpline' # This is an enumerated value, here None is not allowed
  resampledPixelSpacing: # This disables resampling, as it is interpreted as None, to enable it, specify spacing in x, y, z as [x, y , z]
  weightingNorm: # If no value is specified, it is interpreted as None  
  force2D: True
  correctMask: True

voxelSetting:
  kernelRadius: 1
  maskedKernel: False
  voxelBatch: 100

